name: generate-readmes

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  generate-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm

      - name: Install
        run: npm ci

      - name: Format
        run: npm run format

      - name: Generate READMEs
        run: npm run generate

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "--force README.md UP.md CLOSED.md"
          disable_globbing: true
          commit_message: Generate READMEs
